[workspace]
members = [
    ".",
    "example",
]

[package]
name = "axum_session"
version = "0.2.2"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Memory and/or Database Session management layer for axum."
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/axum_session"
keywords = ["Axum", "Tower", "SQLx", "Session", "surrealdb"]
repository = "https://github.com/AscendingCreations/AxumSessions"

[features]
default = ["postgres-rustls"]
sqlite-rustls = ["sqlx/sqlite", "sqlx/runtime-tokio-rustls"]
sqlite-native = ["sqlx/sqlite", "sqlx/runtime-tokio-native-tls"]
postgres-rustls = ["sqlx/postgres", "sqlx/runtime-tokio-rustls"]
postgres-native = ["sqlx/postgres", "sqlx/runtime-tokio-native-tls"]
mysql-rustls = ["sqlx/mysql", "sqlx/runtime-tokio-rustls"]
mysql-native = ["sqlx/mysql", "sqlx/runtime-tokio-native-tls"]
redis-db = ["redis"]
surrealdb-rocksdb =  ["surrealdb/kv-rocksdb", "surrealdb_tag"]
surrealdb-tikv =  ["surrealdb/kv-tikv", "surrealdb_tag"]
surrealdb-indxdb =  ["surrealdb/kv-indxdb", "surrealdb_tag"]
surrealdb-fdb-5_1 =  ["surrealdb/kv-fdb-5_1", "surrealdb_tag", "fdb_tag"]
surrealdb-fdb-5_2 =  ["surrealdb/kv-fdb-5_2", "surrealdb_tag", "fdb_tag"]
surrealdb-fdb-6_0 =  ["surrealdb/kv-fdb-6_0", "surrealdb_tag", "fdb_tag"]
surrealdb-fdb-6_1 =  ["surrealdb/kv-fdb-6_1", "surrealdb_tag", "fdb_tag"]
surrealdb-fdb-6_2 =  ["surrealdb/kv-fdb-6_2", "surrealdb_tag", "fdb_tag"]
surrealdb-fdb-6_3 =  ["surrealdb/kv-fdb-6_3", "surrealdb_tag", "fdb_tag"]
surrealdb-fdb-7_0 =  ["surrealdb/kv-fdb-7_0", "surrealdb_tag", "fdb_tag"]
surrealdb-fdb-7_1 =  ["surrealdb/kv-fdb-7_1", "surrealdb_tag", "fdb_tag"]
surrealdb-mem =  ["surrealdb/kv-mem", "surrealdb_tag"]

#private features.
surrealdb_tag = []
fdb_tag = []

[dependencies]
axum-core = {version = "0.3.4"}
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.95"
time = { version = "0.3", features = ["serde", "macros"] }
tokio = { version = "1.27.0", features = ["full"] }
async-trait = "0.1.68"
tracing = "0.1.37"
thiserror = "1.0.39"
http-body = "0.4.5"
uuid = { version = "1.3.1", features = ["v4", "serde"] }
http = "0.2.9"
tower-layer = "0.3.2"
tower-service = "0.3.2"
sqlx = { version = "0.6.3", default-features = false, features = [
    "time",
    "uuid",
], optional = true }
cookie = { version = "0.17.0", features = ["percent-encode", "private"] }
futures = "0.3.28"
bytes = "1.4.0"
dashmap = "5.4.0"
redis = { version = "0.23.0", features = ["tokio-comp"], optional = true }
surrealdb = { version = "1.0.0-beta.9+20230402", optional = true }

[dev-dependencies]
axum = { version = "0.6.15", features = ["macros"]}
hyper = "0.14.26"
tower = "0.4.13"
log = { version = "0.4.17", default-features = false }

[package.metadata.docs.rs]
features = ["sqlite-rustls","mysql-rustls","redis-db", "surrealdb-rocksdb", "surrealdb-mem"]
rustdoc-args = ["--document-private-items"]
